name: dispatcher
on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            echo "bubu"
