name: dispatcher
on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'galmasi',
              repo: 'workflow-executor',
              workflow_id: 'executortest.yml',
              ref: 'main',
            })
