on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'galmasi',
            repo: 'workflow-executor',
            workflow_id: 'executortest.yml',
            ref: 'master'
          })
