name: dispatches
on: workflow_dispatch
jobs:
  executortest_job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo "This is just job1 test"
  dispatches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo "This is just dispatch test"
    